#!/bin/sh
# Author: Mathieu Charron

# Restore the ALSA config. Save them before deployment using
# `alsa store
alsactl restore

# Start Xorg
/usr/bin/X -nolisten tcp &
while [ 1 ]
do
        sleep 2
        DISPLAY=:0.0 mplayer -idle -slave -quiet -fs -fixed-vo \
        -input file=/tmp/hyberia_slave.fifo > /tmp/hyberia_mplayer.out
        sleep 2
done
