#!/usr/bin/python
#
# Eiffel Forum License, version 2
#
# 1. Permission is hereby granted to use, copy, modify and/or
#    distribute this package, provided that:
#       * copyright notices are retained unchanged,
#       * any distribution of this package, whether modified or not,
#         includes this license text.
# 2. Permission is hereby also granted to distribute binary programs
#    which depend on this package. If the binary program depends on a
#    modified version of this package, you are encouraged to publicly
#    release the modified version of this package.
#
# THIS PACKAGE IS PROVIDED "AS IS" AND WITHOUT WARRANTY. ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE AUTHORS BE LIABLE TO ANY PARTY FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES ARISING IN ANY WAY OUT OF THE USE OF THIS PACKAGE.

"""
Main script for the Touei project. Need the Touei modules.
"""

__author__ = "G-Anime"
__license__ = "Eiffel Version 2"
__version__ = "0.1"
__revision__ = "36"
__contributors__= "Mathieu Charron, Martin Samson"

# Set this to your configuration file.
# default is /etc/touei.conf
CONFIG_FILE = "/etc/touei.conf"
# ALL OTHER CONFIGURATION ARE DONE IN THIS FILE.


###
# Do not change anything below this!
###

# Importation!
import logging
import logging.config
import ConfigParser
import time
import os
import sys
# @TODO Something is fishy.
import touei
from touei import *


if __name__ == "__main__":
    # Create the configParser instance
    config = ConfigParser.SafeConfigParser(touei.CONFIG_DEFAULT_VALUE)
    #print config
    # Check if the config file exists:
    if os.path.exists(CONFIG_FILE):
        #print "Loading config"
        config.read(CONFIG_FILE)
    else: print "Cannot load config"

    # Create Logger
    logger = logging.getLogger("touei")
    logger.setLevel(config.getint('logs', 'debug_level'))

    # Create file handler
    fh = logging.FileHandler(config.get('logs','main_log'))

    # Create the console logging if debug level is 10
    if config.get("logs", "debug_level") == 10:
        ch = logging.StreamHandler()
        cformatter = logging.Formatter("[%(levelname)s] %(name)s - %(message)s")
        ch.setFormatter(cformatter)
        logger.addHandler(ch)

    # Set formating
    formatter = logging.Formatter("%(asctime)s - %(name)s - %(levelname)s - %(message)s")
    fh.setFormatter(formatter)

    # Add the handler to logger
    logger.addHandler(fh)

    # Do some sanity check before starting the system
    # @TODO There is no check for permission
    logger.info("Begin sanity check")
    # Check: video, location
    if not os.path.isdir(config.get('video', 'location')):
        logger.critical("Can't open video location at %s" % (config.get('video', 'location'), ))
        exit(1)
    else:
        logger.debug("Video location %s is usable" % (config.get("video", "location"), ))

    # Check: video, intro
    if not os.path.exists(config.get("video", "intro")):
        logger.critical("Can't open intro video at %s" % (config.get('video', 'intro'), ))
        exit(1)
    else:
        logger.debug("Intro video available at %s" % (config.get("video", "intro") , ))

    # Check: core, slave_socket
    if not os.path.exists(config.get("core", "slave_socket")):
        logger.warn("Can't open the slave socket at %s" % (config.get("core", "slave_socket"), ))
        # Create the socket
        try:
            os.mkfifo(config.get("core", "slave_socket"))
        except OSError:
            logger.critical("Can't create socket file, dying")
            exit(1)
    else:
        logger.debug("FIFO file exist at %s" % (config.get("core", "slave_socket") ,))

    # Check for the temporary folder
    if not os.path.isdir(config.get("video","tmp-location")):
        logger.warn("Temporary location inexistant at %s" % (config.get("video", "tmp-location"), ))
        # Try creating the folders
        try:
            os.mkdir(config.get("video", "tmp-location"))
            os.mkdir(config.get("video", "tmp-location")+"/intro")
            os.mkdir(config.get("video", "tmp-location")+"/ass")
        except OSError:
            logger.critical("Could not create all the folder")
            exit(1)
        finally:
            logger.info("Folders structure created")

    else:
        logger.debug("Tempoary folder exist at %s" % (config.get("video", "tmp-location"), ))

    logger.info("Sanity check complete")

    # Create the mkvutils instance
    mkv = mkvutils.MkvUtils(config)

    # Create the Playlist instance
    playlist = playlist.PlayList(mkv)
    playlist.load(config.get("video", "location"))

    # Create the player instance
    player = player.PlayerInterface(config.get("core", "slave_socket"))

    # Call the daemon
    daemon = daemon.ToueiDaemon(playlist, player, config, mkv)
    # Enter the loop
    daemon.run()

    # We're done
    logger.info("Application run complete")
